const PlanetActionTypes = {
  FETCH_PLANETS_STARTS: "FETCH_PLANETS_STARTS",
  FETCH_PLANETS_SUCCESS: "FETCH_PLANETS_SUCCESS",
  FETCH_PLANETS_FAILURE: "FETCH_PLANETS_FAILURE",
};

export default PlanetActionTypes;
